# Generated by Django 4.2.11 on 2024-05-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareceiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='local',
            field=models.TextField(default=''),
        ),
    ]
